# Generated by Django 4.2.13 on 2024-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0002_uyeler_field_info_uyeler_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyeler',
            name='photo',
            field=models.ImageField(default='.', upload_to='uyeler/'),
        ),
    ]
