# Generated by Django 5.0.6 on 2024-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.CharField(max_length=50)),
                ('konu', models.CharField(max_length=50)),
                ('sinif', models.CharField(max_length=50)),
                ('yazar', models.CharField(max_length=100)),
                ('cevaplandi_mi', models.BooleanField(default=False)),
            ],
        ),
    ]
