# Generated by Django 5.0.6 on 2024-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0002_sorular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='fotograf',
            field=models.ImageField(upload_to='ogrenciler'),
        ),
    ]
