# Generated by Django 5.0.6 on 2024-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0003_alter_ogrenci_fotograf'),
    ]

    operations = [
        migrations.AddField(
            model_name='calismakagitlari',
            name='dosya',
            field=models.FileField(default='.', upload_to='calisma-kagitlari'),
        ),
        migrations.AddField(
            model_name='sorular',
            name='fotograf',
            field=models.ImageField(default='.', upload_to='sorular'),
        ),
    ]
