# Generated by Django 4.2.13 on 2024-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0005_sorular_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorular',
            name='idogrenci',
            field=models.IntegerField(default=-1),
        ),
    ]
