# Generated by Django 5.0.6 on 2024-06-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0006_sorular_idogrenci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=100)),
                ('cevap_metni', models.CharField(max_length=255)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='egitmen.sorular')),
            ],
        ),
        migrations.DeleteModel(
            name='Ogrenci',
        ),
    ]
