# Generated by Django 5.0.6 on 2024-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0007_cevaplar_delete_ogrenci'),
    ]

    operations = [
        migrations.AddField(
            model_name='calismakagitlari',
            name='idegitmen',
            field=models.IntegerField(default=-1),
        ),
    ]
