# Generated by Django 5.0.6 on 2024-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitmen', '0008_calismakagitlari_idegitmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='calismakagitlari',
            name='aciklama',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
